name: Build and Deploy React App to Github Pages

on:
    push:
        branches: [main]
jobs:
    build-and-deploy:
        name: Build and Deploy
        runs-on: ubuntu-latest

        steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Build 
          run: npm install
        
        - name: Test
          run: npm run test

        - name: Deploy
          run: |
            git config --global user.name 'DuckMouse'
            git config --global user.email 'auretswanepoel@gmail.com'
            git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
            npm run deploy